--- #YAML:1.0
name:                ZipTie-Client
version:             1.2
abstract:            Webservice client for the ZipTie server
license:             ~
author:              
    - Leo Bayer <lbayer@ziptie.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    HTTP::Cookies:                 0
    SOAP::Lite:                    0.69
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
